.\" Manpage for vkt command line interface.
.\" Author: Stefan Zellmann (info@szellmann.de).
.TH VKT 1 "February 18 2021" "1.0" "Volkit CLI Manuel"
.SH NAME
vkt \- volkit command line interface
.SH SYNOPSIS
vkt [--version] [--help] <command> [<args>]
.SH DESCRIPTION
The vkt program provides the command line interface (CLI) of the volkit library.
.SH OPTIONS
--version
    Prints the version of the vkt program.

--help
    Prints a help dialog consisting of the synopsis and a list of commands.

.SH SEE ALSO
vkt-render(1), vkt-resample(1)
.SH AUTHOR
Stefan Zellmann (info@szellmann.de)
